#
# Note:  This file is an example.  See k8s/prod/deploy.yaml and k8s/staging/deploy.yaml 
#        for currently deployed versions of CRDs
#

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    k8s-app: domain-name-operator
  name: cloudflarednsrecords.domain-name-operator.tamx.org
spec:
  group: domain-name-operator.tamx.org
  names:
    kind: CloudflareDnsRecord
    plural: cloudflarednsrecords
    singular: cloudflarednsrecord
    shortNames:
      - dns
      - cfdns
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                namespace:
                  type: string
                serviceName:
                  type: string
                hostName:
                  type: string
                domain:
                  type: string
                zoneId:
                  type: string
                proxied:
                  type: boolean
            status:
              type: object
              properties:
                observedGeneration:
                  type: integer
                  format: int64
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
                sync:
                  type: object
                  properties:
                    lastAttemptedAt:
                      type: string
                      format: date-time
                    lastSuccessfulAt:
                      type: string
                      format: date-time
                    lastError:
                      type: object
                      properties:
                        reason:
                          type: string
                        message:
                          type: string
                    retryCount:
                      type: integer
                      format: int32
                      minimum: 0
                cloudflare:
                  type: object
                  properties:
                    state:
                      type: string
                    zoneId:
                      type: string
                    zoneName:
                      type: string
                    recordId:
                      type: string
                    hostname:
                      type: string
                    ip:
                      type: string
                    proxied:
                      type: boolean
                    ttl:
                      type: integer
                      format: int32
                history:
                  type: array
                  maxItems: 10
                  items:
                    type: object
                    properties:
                      timestamp:
                        type: string
                        format: date-time
                      action:
                        type: string
                      status:
                        type: string
                      message:
                        type: string
                      cloudflareRecordId:
                        type: string
                      hostname:
                        type: string
                      zoneId:
                        type: string
                      ip:
                        type: string
                      proxied:
                        type: boolean
                      state:
                        type: string
                      ttl:
                        type: integer
                        format: int32
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Host
          type: string
          jsonPath: .status.cloudflare.hostname
        - name: State
          type: string
          jsonPath: .status.cloudflare.state
        - name: Zone
          type: string
          jsonPath: .status.cloudflare.zoneId
        - name: Synced
          type: string
          jsonPath: .status.conditions[?(@.type=="Synced")].status
        - name: LastSuccess
          type: date
          jsonPath: .status.sync.lastSuccessfulAt
