---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    k8s-app: domain-name-operator
  name: cloudflarednsrecords.domain-name-operator.tamx.org
spec:
  group: domain-name-operator.tamx.org
  names:
    kind: CloudflareDnsRecord
    plural: cloudflarednsrecords
    singular: cloudflarednsrecord
    shortNames:
      - dns
      - cfdns
  #scope: Cluster
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                namespace:
                  type: string
                serviceName:
                  type: string
                hostName:
                  type: string
                domain:
                  type: string
                zoneId:
                  type: string
                proxied:
                  type: boolean
      additionalPrinterColumns: []
