---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    k8s-app: domain-name-operator
  name: cloudflarednsrecords.domain-name-operator.tamx.org
spec:
  additionalPrinterColumns: []
  group: domain-name-operator.tamx.org
  names:
    kind: CloudflareDnsRecord
    plural: cloudflarednsrecords
    singular: cloudflarednsrecord
    shortNames:
      - dns
      - cfdns
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                namespace:
                  type: string
                serviceName:
                  type: string
                hostName:
                  type: string
                domain:
                  type: string
                zone_id:
                  type: string



---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    k8s-app: domain-name-operator
  name: domain-name-operator
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
  - apiGroups:
      - domain-name-operator.tamx.org
    resources:
      - cloudflare_dns_records
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - '*'

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: domain-name-operator
  name: domain-name-operator
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    k8s-app: domain-name-operator
  name: domain-name-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: domain-name-operator
subjects:
  - kind: ServiceAccount
    name: domain-name-operator
    namespace: default
