---
apiVersion: domain-name-operator.tamx.org/v1
kind: CloudflareDnsRecord
metadata:
  name: test-record
  labels:
    app: test-app
  namespace: test-record
spec:
  namespace: test-record
  serviceName: test-service
  hostName: test-service
  domain: ameelio.xyz
  zoneId: 53eb2f3db04afdb3a9fca95bf5b27d10

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-app
  name: test-service
  namespace: test-record
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-size-slug: "lb-small" # or lb-medium|lb-large
spec:
  type: LoadBalancer
  selector:
    app: test-record
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4000
